# Generated by Django 4.2.3 on 2023-07-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_text', models.TextField()),
                ('rating', models.FloatField()),
                ('reviewer_name', models.CharField(max_length=50)),
                ('date_added', models.DateTimeField()),
                ('num_votes', models.IntegerField()),
            ],
        ),
    ]
